### ISSUE TITLE
error using cron to run iotstack_backup

### ISSUE THREAD

**Issue by mountain-pitt** [Paraphraser/IOTstackBackup#3]
I have setup IOTstack Backup and Restore ad per guide.
Method.  RSYNC   to a second machine (Rapberry Pi 4).
Both machines are Raspberry Pi with IOTstack installed aswell.
Using user id = pi on both machines and paswords are the same.
Have installed SSH "Setting up SSH keys for password-less access" tested from both machines. OK
Second machine created folder /storage    (Backups will be stored here).
From 1st machine. logged in as pi.    (Docker-3)
pi@Docker-3:~ $ iotstack_backup
Backup files are created in 2nd machine OK.  (Docker-4).

Set up crontab as instructed.  a below 

SHELL=/bin/bash
HOME=/home/pi
PATH=/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# backup Docker containers and configurations once per day at 11:00am
00	11	*	*	*	iotstack_backup >>./Logs/iotstack_backup.log 2>&1

I adjusted to this as 11:00 am didn't work

Run every 10 min for testing
*/10	*	*	*	*	iotstack_backup >>./Logs/iotstack_backup.log 2>&1

either of the entries does not work.

I then do sudo service cron status

pi@Docker-3:~ $ sudo service cron status
● cron.service - Regular background program processing daemon
   Loaded: loaded (/lib/systemd/system/cron.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2021-08-01 12:53:22 AEST; 1h 30min ago
     Docs: man:cron(8)
 Main PID: 392 (cron)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/cron.service
           └─392 /usr/sbin/cron -f

Aug 01 14:10:01 Docker-3 CRON[8943]: pam_unix(cron:session): session closed for user root
Aug 01 14:15:01 Docker-3 CRON[9245]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 01 14:15:01 Docker-3 CRON[9246]: (root) CMD (influx_backup >>./Logs/iotstack_backup.log 2>&1 )
Aug 01 14:15:01 Docker-3 CRON[9245]: pam_unix(cron:session): session closed for user root
Aug 01 14:17:01 Docker-3 CRON[9338]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 01 14:17:01 Docker-3 CRON[9339]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 01 14:17:01 Docker-3 CRON[9338]: pam_unix(cron:session): session closed for user root
Aug 01 14:20:01 Docker-3 CRON[9555]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 01 14:20:01 Docker-3 CRON[9556]: (root) CMD (influx_backup >>./Logs/iotstack_backup.log 2>&1 )
Aug 01 14:20:01 Docker-3 CRON[9555]: pam_unix(cron:session): session closed for user root
pi@Docker-3:~ $

Am at a loss to why it works at terminal mode but cron does not.

**Comment by Paraphraser** [comment]
Is it possible that you created your crontab with `sudo crontab -e` rather than just `crontab -e` ?

If so, that might explain what you are seeing.

I'm guessing about this from the `(root)` in `(root) CMD (influx_backup >>./Logs/my_influx_backup.log 2>&1)`. On my own system, a cron task firing will always have `(pi)` in the position where your output shows `(root)`.

If cron is running the jobs for root then the `./Logs` directory is the absolute path `/root/Logs`. If that directory exists, it should have logs about what has been going on. If it doesn't exist then you could try `sudo mail` because that's where `cron` shoves stuff if it can't write to a log file.

If this **does** turn out to be the answer then:

1. This definitely explains why running a backup at the terminal works while running it from cron does not. If you try to run any of the backup and restore routines with `sudo` in front, it will tell you not to do that.
2. Maybe also read [a word about sudo](https://sensorsiot.github.io/IOTstack/Getting-Started#a-word-about-the-sudo-command) in the IOTstack getting started document.

**Comment by mountain-pitt** [comment]
Deleted the sudo crontab -e entry.
Started again
crontab -e

Added the above entry again for testing.
Perfect getting backups every 10 min. 

Aug 01 14:50:01 Docker-3 CRON[11773]: (pi) CMD (iotstack_backup >>./Logs/iotstack_backup.log 2>&1)
Aug 01 14:50:04 Docker-3 sudo[11786]:       pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/chown : /home/pi/IOTstack/backups
Aug 01 14:50:04 Docker-3 sudo[11786]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 01 14:50:04 Docker-3 sudo[11786]: pam_unix(sudo:session): session closed for user root
Aug 01 14:50:05 Docker-3 sudo[11807]:       pi : TTY=unknown ; PWD=/home/pi/IOTstack/backups ; USER=root ; COMMAND=/usr/bin/tar -czf /home/pi/IOTstack/backups/2021-08-01_1450.Docker-3.general-backup.tar.gz -C /h
Aug 01 14:50:05 Docker-3 sudo[11807]: pam_unix(sudo:session): session opened for user root by (uid=0)

Don't know what the TTY=unknown is.

Thanks for the info and I read your link on SUDO etc..
Today I have learnt more. 

Your Setup/Guide is perfect and easy to understand .

Thanks again

**Comment by Paraphraser** [comment]
I've added some more words to the crontab section - gives the actual (sudo-less) commands rather than assuming everyone "just knows" how to set up a crontab. With any luck, that will reduce the risk of anyone else falling into the same trap.

Thanks for the feedback.
